on:
  push:
    paths:
    - 'sch.ac.kr'
  # schedule:
  #   # 한국 표준시 오후 2시에 2주 간격으로 실행
  #   - cron: '0 5 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - working-directory: ./sch.ac.kr
      run: dotnet build --configuration Release
