name: Sync sch.ac.kr

on:
  push:
    paths:
      - .github/workflows/sch.ac.kr.yml
      - 'sch.ac.kr/**'
  schedule:
    # 한국 표준시 오후 2시에 2주 간격으로 실행
    - cron: '0 5 */14 * *'

env:
  ICAL_SOURCE: sch.ac.kr
  ICAL_NAME: 순천향대학교 학사일정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          path: src
      - name: Build
        run: dotnet build src/$ICAL_SOURCE
      - name: Checkout destination branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: dist
      - name: Update iCalendar file
        run: dotnet run --project src/$ICAL_SOURCE -- dist/ical/$ICAL_SOURCE.ics
      - name: Update metadata file
        working-directory: dist/ical
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Update metadata."
            jq -cn \
              --arg now "$(date -u +"%FT%T.%3NZ")" \
              --arg name "$ICAL_NAME" \
              '
                .updated_at |= $now
                | .source |= "'$ICAL_SOURCE'"
                | .name |= $name
                | .filename |= "ical/'$ICAL_SOURCE'.ics"
              ' > $ICAL_SOURCE.json
          fi
      - name: Commit and push changes
        working-directory: dist
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'Github Action'
          git add .
          git commit -m "Sync $ICAL_SOURCE"
          git push
