on:
  push:
    paths:
      - sch.ac.kr
      - .github/workflows/sch.ac.kr.yml
  schedule:
    # 한국 표준시 오후 2시에 2주 간격으로 실행
    - cron: '0 5 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          path: src
      - name: Build bot
        run: dotnet build src/sch.ac.kr
      # TODO: Global lock that queues workflow jobs.
      - name: Checkout destination branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: dist
      - name: Run bot
        run: dotnet run --project src/sch.ac.kr -- dist/ical/sch.ac.kr.ics
      - name: Update metafile
        working-directory: dist
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are changes."
            if [ ! -f "ical.json" ]; then
              echo "Initialize metafile."
              echo "{}" > ical.json
            fi
            echo "Update metafile."
            cat ical.json | jq \
              --arg now "$(date -u +"%FT%T.000Z")" \
              '
                .updated_at |= $now
                | .data."sch.ac.kr".name |= "순천향대학교 학사일정"
                | .data."sch.ac.kr".path |= "ical/sch.ac.kr.ics"
                | .data."sch.ac.kr".source |= "sch.ac.kr"
                | .data."sch.ac.kr".updated_at |= $now
              ' > ical.json
          fi
      - name: Commit changes
        working-directory: dist
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'Github Action'
          git add .
          git commit -m 'Sync sch.ac.kr'
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: dist
