on:
  push:
    paths:
      - sch.ac.kr
      - .github/workflows/sch.ac.kr.yml
  schedule:
    # 한국 표준시 오후 2시에 2주 간격으로 실행
    - cron: '0 5 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ICAL_SOURCE: sch.ac.kr
      ICAL_NAME: 순천향대학교 학사일정
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          path: src
      - name: Build bot
        run: dotnet build src/$ICAL_SOURCE
      # TODO: Global lock that queues workflow jobs.
      - name: Checkout destination branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: dist
      - name: Update iCalendar file
        run: dotnet run --project src/$ICAL_SOURCE -- dist/ical/$ICAL_SOURCE.ics
      - name: Update metadata file
        working-directory: dist/ical
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Update metadata."
            echo "{}" | jq -c \
              --arg now "$(date -u +"%FT%T.000Z")" \
              '
                .updated_at |= $now
                | .source |= "'$ICAL_SOURCE'"
                | .name |= "'$ICAL_NAME'"
                | .filename |= "ical/'$ICAL_SOURCE'.ics"
              ' > $ICAL_SOURCE.json
          fi
      - name: Commit changes
        working-directory: dist
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'Github Action'
          git add .
          git commit -m "Sync $ICAL_SOURCE"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: dist
