name: Sync sch.ac.kr

on:
  push:
    paths:
      - .github/workflows/sch.ac.kr.yml
      - 'ical/sch.ac.kr/**'
  schedule:
    # 한국 표준시 오후 2시에 2주 간격으로 실행
    - cron: '0 5 */14 * *'

env:
  ICAL_SOURCE: sch.ac.kr
  ICAL_NAME: 순천향대학교 학사일정

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Checkout application branch
        uses: actions/checkout@v2
        with:
          path: app
      - name: Build
        run: dotnet build app/ical/$ICAL_SOURCE
      - name: Checkout distribution branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: dist
      - name: Update iCalendar file
        run: dotnet run -p app/ical/$ICAL_SOURCE/src -- -f dist/ical/$ICAL_SOURCE.ics
      - name: Update metadata file
        run: dist/update-ical.sh
      - name: Commit and push changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'Github Action'
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync $ICAL_SOURCE"
          git push
        working-directory: dist
